---
# Sidekiq configuration file

# Set the concurrency (number of threads)
:concurrency: 5

# Queues to process (with their priorities)
:queues:
  - herf_app_mvp_2025_v1_production_default
  - herf_app_mvp_2025_v1_production_mailers
  - herf_app_mvp_2025_v1_production_low_priority
  - default
  - mailers
  - low_priority

# Redis connection settings
:redis:
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>

# Timeout for job execution (in seconds)
:timeout: 25
